Adding nulling and explicit columns filter to outputs
DemocratizingData/data-ingest pull request #6
Opened 2023-01-10 15:49 UTC by amitschang

In cases where an entire column has no non-null values, the mapping will be missing from the json entirely and as such column will be missing. Since the database still expects values we need to provide these null-filled. Being more explicit here, while a little clunky, has the advantage that we can fail fast when required columns are missing.  The view of required and nullable from the DB perspective is not necessarily the same as for the json data, optional here means the entire dataset could be missing the column.

Also adding deduplication to the dyads table, which has been seen to have redundant entries for model for example.

2023-01-17 15:54 UTC, glemson requested changes

2023-01-17 16:14 UTC, amitschang commented on susdingest/jsonloader.py
> +        publications['tested_expressions'] = publications['expressions'] \
it is possible, it is added above as an optional col.

2023-01-17 16:14 UTC, amitschang commented on susdingest/jsonloader.py
> +            publications, required_cols, optional_cols + ['journal_citescore_year', 'journal_citescore_value']) \
quite right. I suppose I need to add a test to excersize all optional columns - would have caught this. Thanks!

2023-01-17 16:16 UTC, glemson commented on susdingest/jsonloader.py
> +        publications['tested_expressions'] = publications['expressions'] \
ah yes, missed that statement. but should the column name not be 'tested_expressions'

2023-01-17 18:04 UTC, amitschang commented
I've updated and added tests for the optional/required columns. Shouldn't have skimped in the first place since it brought out an issue in null checks, which don't work the same between pd.NA and np.nan null types, so added a function to coalesce those checks.

2023-01-18 21:55 UTC, glemson approved these changes
go for it

2023-01-18 22:21 UTC, merged